apiVersion: connectors.aiops.ibm.com/v1beta1
kind: BundleManifest
metadata:
  name: java-grpc-connector-template
spec:
  prereqs:
    repo: 'https://github.com/mahantidinesh7/cp4waiops-connectors-java-template'
    branch: Fix
    authSecret:
      name: test-utilities-github-token
    components:
      - name: deployment
        path: /bundle-artifacts/prereqs
        type: kustomize
        kustomization:
          images:
            - name: java-grpc-connector-template
              newName: docker.io/mahantidinesh/java-grpc-connector-template
              newTag: four
  instanced:
    repo: 'https://github.com/mahantidinesh7/cp4waiops-connectors-java-template'
    branch: Fix
    authSecret:
      name: test-utilities-github-token
    components:
      - name: connector
        path: /bundle-artifacts/connector
        type: kustomize
        kustomization:
          images:
            - name: java-grpc-connector-template
              newName: docker.io/mahantidinesh/java-grpc-connector-template
              newTag: four
