apiVersion: connectors.aiops.ibm.com/v1beta1
kind: ConnectorSchema
metadata:
  name: java-grpc-connector-template
spec:
  categories:
  - events
  ceType: com.ibm.aiops.connectors.configuration
  components:
  - apiType: AsyncAPI
    name: connector
  documentation: https://github.ibm.com/quicksilver/cp4waiops-grpc-templates/blob/master/open-liberty/README.md
  permissions:
    channels:
      - name: cp4waiops-cartridge.analyticsorchestrator.metrics.itsm.raw
        operations:
          - write
      - name: cp4waiops-cartridge.connector-generic.svc_topology.connector_report
        operations:
          - write
      - name: cp4waiops-cartridge.lifecycle.input.events
        operations:
          - write
  schema:
    additionalProperties: false
    oneOf:
    - required:
      - enableGatherMetrics
    properties:
      enableGatherMetrics:
        type: boolean
        description: Enables or disables metric connector template
        default: true
      metricName:
        type: string
        description: Name of metric to generate
        default: Usage%
      deploymentType:
        type: string
        description: Dictates if deployment is local or remote
        default: local
      display_name:
        description: Display name of the connection
        type: string        
    type: object
  uiSchema:
    type: java-grpc-connector-template
    displayName: "IM"
    categories:
    - "{{connector.common.category.events}}"
    url: https://ibm.biz/int-github
    isObserver: false
    deploymentType: ["local", "remote"]
    apiAdaptor: connection
    datasourceType: events
    sidePanelTitle: "IM"
    sidePanelDescription: "{{connector.elk.description}}"
    sidePanelInfoHeader: "Information"
    sidePanelInfo:
    - "TODO"
    hasOptionalConfig: false
    hasOptionalText: false
    hasAIModelType: false
    formSteps:
    - step:
        id: addConnection
        name: "{{formSteps.addConnection}}"
    form:
    - id: name
      element: input
      type: text
      label: "{{connector.common.form.uniqueID.label}}"
      placeholder: "{{connector.common.form.ops_integration_name.placeholder}}"
      apiMapping: connection_config.display_name
      formStep: addConnection
      isRequired: true
    - id: enableGatherMetrics
      apiMapping: connection_config.enableGatherMetrics
      element: toggleForm
      defaultToggled: true
      items:
        - "{{common.Off}}"
        - "{{common.On}}"
      itemKeys: [true, false]
      description: "Enables or disables metric connector template"
      headerLabel: "Enable gathering of connector metrics"
      isRequired: true
      formStep: addConnection
      form:
        - id: false
        - id: true
          rows:
            - id: metricName
              element: input
              type: text
              label: "Metric name"
              placeholder: "Usage%"
              defaultValue: Usage%
              helperText: "Assign a name to the generated metric data."
              apiMapping: connection_config.metricName
              formStep: addConnection
              isRequired: true
    - apiMapping: connection_config.deploymentType
      element: input
      formStep: addConnection
      id: orchestration
      itemKeys:
      - local
      - microedge
      items:
      - '{{connection_form.dynamic_item.local}}'
      - '{{connection_form.dynamic_item.remote}}'
      label: '{{connector.common.form.orchestration.label}}'
      type: radio
